### ISSUE TITLE
LatLng issue

### ISSUE THREAD

**Issue by thorizer** [nkdkhanh46/flutter_map_directions#2]
The name 'LatLng' is defined in the libraries 'package:flutter_map_directions/src/latlng.dart (via package:flutter_map_directions/flutter_map_directions.dart)' and 'package:latlong2/latlong.dart'.
Try using 'as prefix' for one of the import directives, or hiding the name from all but one of the imports

**Comment by nkdkhanh46** [comment]
@thorizer flutter_map_directions.LatLng class has been renamed to DirectionCoordinate in v0.0.4.
You can import and use latlong2.LatLng as usual.
