### ISSUE TITLE
how draw line for follow the road

### ISSUE THREAD

**Issue by Flouzl** [nkdkhanh46/flutter_map_directions#4]
hello I would like to know how we can draw the line for which follows the road because I did not understand example: /

**Comment by nkdkhanh46** [comment]
@Flouzl You just need to provide _coordinates_ list for DirectionsLayer widget

For ex:

```
final coordinates = [
  DirectionCoordinate(10.776983,106.690581),
  DirectionCoordinate(10.780691,106.658819)
];

...

DirectionsLayer(
  coordinates: coordinates,
)
```

**Comment by Flouzl** [comment]
ok thanks but my prombles is not working with geolocalation 

`import 'package:flutter_map_directions/flutter_map_directions.dart';
import 'package:geolocator/geolocator.dart';


override
  void initState() {
    super.initState();
    _timer = Timer.periodic(Duration(milliseconds: 500), (timer) {
      if (mounted) {
        _getCurrentLocation();
      }
    });
  }

  @override
  void dispose() {
    _timer?.cancel(); 
    super.dispose();
  }

  

  Future<void> _getCurrentLocation() async {
    LocationPermission permission = await Geolocator.requestPermission();

    if (permission == LocationPermission.denied) {
    } else if (permission == LocationPermission.whileInUse) {
    } else if (permission == LocationPermission.always) {
    }


    Position position = await Geolocator.getCurrentPosition();
    setState(() {
      _currentPosition = position;
    });
  } 
  `
  
  @override
  Widget build(BuildContext context) {
      final coordinates = [
      DirectionCoordinate(51.509093, -0.094151),
      if (_currentPosition != null)
      DirectionCoordinate(_currentPosition!.latitude,_currentPosition!.longitude)
    ];
    
    ...

     DirectionsLayer(
        coordinates: coordinates,
        color: Colors.deepOrange
      ),




`

**Comment by nkdkhanh46** [comment]
@Flouzl Can you provide the value of __currentPosition_?

**Comment by Flouzl** [comment]
' Position? _currentPosition; '

**Comment by nkdkhanh46** [comment]
@Flouzl I mean the real value, after _Geolocator .getCurrentPosition_ success

**Comment by Flouzl** [comment]
is 51.509093, -0.094151

**Comment by Flouzl** [comment]
but i can change the location whene i want

**Comment by nkdkhanh46** [comment]
@Flouzl I've found the cause. Current version of the plugin doesn't support state change.
I'll update it soon to make it work.

**Comment by Flouzl** [comment]
okay thank you

**Comment by nkdkhanh46** [comment]
@Flouzl You can update the route in v0.0.5 using _DirectionController_.
You should update the map bounds to fit the new coordinates.
Take a look on the example for more details

**Comment by Flouzl** [comment]
thanks for the update but he don't creating the line 

`  void _loadRoute() async {
    await Future.delayed(const Duration(seconds: 5));
    _coordinates = [
      DirectionCoordinate(51.509093, -0.094151),
      if (_currentPosition != null)
      DirectionCoordinate(_currentPosition!.latitude,_currentPosition!.longitude)
      ]; // new coordinates after awaiting
    _directionController.updateDirection(_coordinates);
  }
  `
  
  
  `     DirectionsLayer(
        coordinates: _coordinates,
        color: Colors.deepOrange,
        controller: _directionController
      ),`

**Comment by nkdkhanh46** [comment]
@Flouzl Did you try to run the example?

Possible issue with your app:

1. _currentPosition is null => the route is not available if coordinates list has lest than 2 items.
2. You didn't update the maps bounds to make the route appear on visible area

**Comment by Flouzl** [comment]
i think is because my current Position is null when i start my app but after 2 sec my current Position not null and i dont see how i can change this

**Comment by nkdkhanh46** [comment]
@Flouzl You should call `directionController.updateDirection` after getting current position completed:

```
Position position = await Geolocator.getCurrentPosition();

final coordinates = [
   <start coordinate>,
  <currentPosition coordinate>
]

_directionController.updateDirection(_coordinates);
```

**Comment by Flouzl** [comment]
`
Position position = await Geolocator.getCurrentPosition(); 
 void _loadRoute() async {
    await Future.delayed(const Duration(seconds: 1));
    final _coordinates = [
      DirectionCoordinate(51.509093, -0.094151),
      if (_currentPosition != null)
      DirectionCoordinate(_currentPosition!.latitude,_currentPosition!.longitude) 

      ]; // new coordinates after awaiting
    _directionController.updateDirection(_coordinates);
  }
  
`

like this

**Comment by nkdkhanh46** [comment]
@Flouzl You don't need `await Future.delayed(const Duration(seconds: 1));`. It's the simulation for waiting an async action.

In you app it's corresponding with `Position position = await Geolocator.getCurrentPosition();`

**Comment by Flouzl** [comment]
i didn't work

**Comment by nkdkhanh46** [comment]
You can share your code here if possible. I'll take a look on it: https://codeshare.io/gL7qRy

**Comment by Flouzl** [comment]
okay

**Comment by Flouzl** [comment]
but you can delete after pls

**Comment by nkdkhanh46** [comment]
> but you can delete after pls

@Flouzl Sure.
I've updated your code, you can try again

**Comment by Flouzl** [comment]
okay thanks is working
