### ISSUE TITLE
Support for flutter_map version 6

### ISSUE THREAD

**Issue by kcoyner** [nkdkhanh46/flutter_map_directions#5]
Looking forward to support for flutter_map version 6.  Thank you.

**Comment by nkdkhanh46** [comment]
@kcoyner the plugin will be updated soon to support flutter_map v6

**Comment by nkdkhanh46** [comment]
@kcoyner the plugin has been updated to support latest version of flutter_map (v7.0.2) and latlong2 (v0.9.1)
