### ISSUE TITLE
update for flutter_map version 7 and latlong2 version ^0.9.1

### ISSUE THREAD

**Issue by Flouzl** [nkdkhanh46/flutter_map_directions#6]
hi, is it possible to update the package to flutter map 7 and latlong2 ^0.9.1 thanks in advance

**Comment by nkdkhanh46** [comment]
I'll try to update it next week, thanks for waiting

**Comment by Flouzl** [comment]
thank you very much for the quick response

**Comment by nkdkhanh46** [comment]
@Flouzl v0.0.6 has been released which is using flutter_map v7.0.2 + latlong2 v0.9.1
