### ISSUE TITLE
Distance?

### ISSUE THREAD

**Issue by JacoFourie** [nkdkhanh46/flutter_map_directions#7]
Hi. Thanks for a great lib. Is there a way to get the distance from the route?

**Comment by JacoFourie** [comment]
Is see there is a distance and duration field in the json that is returned from OSRM. Could you make that available also, please?

**Comment by nkdkhanh46** [comment]
@JacoFourie distance & duration have been available on OsrmRoute object from v0.0.7

**Comment by JacoFourie** [comment]
Great how do I get to them ?

**Comment by nkdkhanh46** [comment]
@JacoFourie It is returned in `onCompleted` event. You need to update to v0.0.8 of the plugin

You can check `main.dart` for an example

**Comment by JacoFourie** [comment]
Thanks, it works great.
